### ISSUE TITLE
Implement Location Search

### ISSUE THREAD

**Issue by bsogata** [wengdg/reefnexus#19]
The Location page currently displays nothing unless the user navigates to the page through selecting a location from the index page.  Since this is not particularly useful, it might be good to allow users to search through all locations in the database while on the Location view.  This could be implemented through a drop-down menu where the user can look through all of the locations available, or as an autocomplete text field; the former could be difficult to scroll through whereas the latter would not initially show the users what options are available.

**Comment by wengdg** [comment]
Location search was implemented as a dropdown and successful.
